upstream docker {
  server 127.0.0.1:3000;
}

server {
  root /usr/share/nginx/freks.jp;
  index  index.html index.htm;

  listen 443 ssl;
  server_name freks.jp;

  ssl_certificate /etc/letsencrypt/live/freks.jp/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/freks.jp/privkey.pem;

  ssl_session_cache   shared:SSL:3m;
  ssl_buffer_size     8k;
  ssl_session_timeout 10m;

  # 2048bit 推奨
  ssl_dhparam /etc/ssl/private/dhparam.pem;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
  ssl_prefer_server_ciphers on;

  # HTTPS のみでサービスを提供する場合にだけ設定
  add_header Strict-Transport-Security max-age=15768000;

  add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
#  add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' https: 'unsafe-inline' https:; script-src 'self' https://maps.googleapis.com https://maps.gstatic.com; object-src 'self';";
  etag off;

  access_log  /var/log/nginx/freks-access.log  main;
  error_log  /var/log/nginx/freks-error.log warn;

  gzip  on;
  gzip_static on;
  gzip_types text/css text/javascript application/javascript;
  gzip_http_version 1.1;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 9;

  # 末尾スラッシュなしのディレクトリURLを末尾スラッシュありにリダイレクト
  # rewrite ^(/apps/[^/]+)$ $1/ permanent;

  # 末尾スラッシュの自動追加(ディレクトリのみ)
  absolute_redirect off;

  location /apps/ {
    try_files $uri $uri/ =404;
  }

  location = /.well-known/ {
    access_log           off;
    log_not_found        off;
    autoindex            off;
    return 404;
  }

  error_page 404 /404.html;
  location = /404.html {
    internal;
  }

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    internal;
  }
}

server {
  listen       443 ssl;
  server_name  www.freks.jp;
  return 301 https://freks.jp$request_uri;
}

server {
  listen       80;
  server_name  freks.jp www.freks.jp;
  return 301 https://freks.jp$request_uri;
}

